name: gcputils
description: An easy way to use Google Cloud Platform services in dart.

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  googleapis: 0.54.0
  googleapis_auth: 0.2.11

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
